#!/bin/bash
#
# from: https://stackoverflow.com/questions/54578066/how-to-build-a-docker-image-on-a-specific-architecture-with-docker-hub
-
BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)

# if it has no target architecture, do nothing
[ "${BUILD_ARCH}" == "Dockerfile" ] && \
    { echo 'qemu-user-static: Registration not required for current arch'; exit 0; }

docker run --rm --privileged multiarch/qemu-user-static:register --reset
